In [1]:
import numpy as np

print(np.__version__)

1.26.4


# Array creation

## 1.Converting Python sequences to NumPy arrays

In [2]:
# 1D array
a1D = np.array([1, 2, 3, 4])
print("a1D =", a1D)

# 2D array
a2D = np.array([[1, 2], [3, 4]])
print("a2D =\n", a2D)

a1D = [1 2 3 4]
a2D =
 [[1 2]
 [3 4]]


## 2.Intrinsic NumPy array creation functions

1D array

In [3]:
# arange
arr1 = np.arange(2, 11, 2)
print("arr1 =", arr1)

arr1 = [ 2  4  6  8 10]


In [4]:
# linspace
arr2, step = np.linspace(1, 10, num=10, endpoint=True, retstep=True)
print("arr2 =", arr2)
print("step =", step)

arr2 = [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
step = 1.0


2D array

In [5]:
# Identity-like matrix 
eye_mat = np.eye(4, 3)
print("np.eye(4, 3) =\n", eye_mat)

np.eye(4, 3) =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [6]:
# Diagonal matrix from list, shifted by k=1
diag1 = np.diag([1, 2, 3], k=1)
print("np.diag([1, 2, 3], k=1) =\n", diag1)

# Extract diagonal with offset from 2D array
diag2 = np.diag([[1, 2, 1], [3, 4, 1]], k=1)
print("\nnp.diag([[1, 2, 1], [3, 4, 1]], k=1) =\n", diag2)

np.diag([1, 2, 3], k=1) =
 [[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]

np.diag([[1, 2, 1], [3, 4, 1]], k=1) =
 [2 1]


In [7]:
# Vandermonde matrix
vander_mat = np.vander((1, 2, 3, 4), 4)
print("np.vander((1, 2, 3, 4), 4) =\n", vander_mat)

np.vander((1, 2, 3, 4), 4) =
 [[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


general nD array

In [8]:
# Fill with zeros
zeros_arr = np.zeros((3, 3, 2), order="C")
print("np.zeros((3, 3, 2), order='C') =\n", zeros_arr)

np.zeros((3, 3, 2), order='C') =
 [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [9]:
# Fill with ones
ones_arr = np.ones((3, 3, 2), order="F")
print("np.ones((3, 3, 2), order='F') =\n", ones_arr)

np.ones((3, 3, 2), order='F') =
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [10]:
# Fill with random values between 0 and 1
from numpy.random import default_rng
rng = default_rng(42)
rand_arr = rng.random((3, 3, 2))
print("default_rng(42).random((3, 3, 2)) =\n", rand_arr)

default_rng(42).random((3, 3, 2)) =
 [[[0.77395605 0.43887844]
  [0.85859792 0.69736803]
  [0.09417735 0.97562235]]

 [[0.7611397  0.78606431]
  [0.12811363 0.45038594]
  [0.37079802 0.92676499]]

 [[0.64386512 0.82276161]
  [0.4434142  0.22723872]
  [0.55458479 0.06381726]]]


In [11]:
# Indices 
idx = np.indices((2, 3, 4), sparse=True)
print("np.indices((2, 3, 4), sparse=True) =")
for i, arr in enumerate(idx):
    print(f"Dimension {i}:\n{arr}\n")

np.indices((2, 3, 4), sparse=True) =
Dimension 0:
[[[0]]

 [[1]]]

Dimension 1:
[[[0]
  [1]
  [2]]]

Dimension 2:
[[[0 1 2 3]]]



## 3.Replicating, joining, or mutating existing arrays

view

In [12]:
origin = np.zeros(4)
view = origin[:2]
view += 1
print('origin =', origin, 'view =', view)

origin = [1. 1. 0. 0.] view = [1. 1.]


copy

In [13]:
origin = np.zeros(4)
copy = origin[:2].copy()
copy += 1
print('origin =', origin, 'copy =', copy)

origin = [0. 0. 0. 0.] copy = [1. 1.]


join

In [56]:
A = np.diag([1, 2, 3])   
B = np.vander((1, 2, 3), 3)  
print("A =\n", A, "\n")
print("B =\n", B, "\n")

C1 = np.block([A, B])
print("np.block([A, B]) =\n", C1, "\n")
C2 = np.block([[A], [B]])
print("np.block([[A],[B]]) =\n", C2)

A =
 [[1 0 0]
 [0 2 0]
 [0 0 3]] 

B =
 [[1 1 1]
 [4 2 1]
 [9 3 1]] 

np.block([A, B]) =
 [[1 0 0 1 1 1]
 [0 2 0 4 2 1]
 [0 0 3 9 3 1]] 

np.block([[A],[B]]) =
 [[1 0 0]
 [0 2 0]
 [0 0 3]
 [1 1 1]
 [4 2 1]
 [9 3 1]]


## 4.Attribute

In [136]:
a = np.arange(10).reshape(5, 2)
print('dimensions: ', a.ndim)
print('shape: ', a.shape)
print('size: ', a.size)

dimensions:  2
shape:  (5, 2)
size:  10


# Indexing

## 1.Basic indexing

Single element indexing

In [100]:
x = np.arange(10)
x.shape = (2, 5)
print(x)
print(x[1, 3])

[[0 1 2 3 4]
 [5 6 7 8 9]]
8


array([4, 9])

Slicing and striding

In [16]:
x = np.arange(10)
print("x[1:7:2] =", x[1:7:2])   
print("x[7:1:-2] =", x[7:1:-2]) 

x[1:7:2] = [1 3 5]
x[7:1:-2] = [7 5 3]


In [17]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print("x.shape =", x.shape)
print("x[1:2, 0:2] =\n", x[1:2, 0:2])

x.shape = (2, 3, 1)
x[1:2, 0:2] =
 [[[4]
  [5]]]


Dimensional indexing tools

In [18]:
# Ellipsis
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print(x[0, ...])  

[[1]
 [2]
 [3]]


In [19]:
print(x[:, np.newaxis, :, :].shape)

(2, 1, 3, 1)


In [54]:
# Broadcasting with None/np.newaxis
x = np.arange(5)
print(x[:, None] + x[None, :])

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


## 2.Advanced indexing

Integer array indexing

In [3]:
x = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])
# Single index array
print(x[ [0, -1] ], '\n')

# Multiple index array
print(x[ [0, -1], [0, -1] ])

[[1 2]
 [5 6]] 

[1 6]


In [4]:
# Multidimensional index array
index_array1 = np.array([[0], 
                         [-1]])
print('Index array shape: ',  index_array1.shape)
print(x[index_array1], '\n with shape: ', x[index_array1].shape, '\n')

index_array2 = np.array([[0,-1]])
print('Index array shape: ',  index_array2.shape)
print(x[index_array2], '\n with shape: ', x[index_array2].shape)

Index array shape:  (2, 1)
[[[1 2]]

 [[5 6]]] 
 with shape:  (2, 1, 2) 

Index array shape:  (1, 2)
[[[1 2]
  [5 6]]] 
 with shape:  (1, 2, 2)


In [5]:
# Broadcasting index array
array = np.array([0, -1])
row = array[None, :]
rows = np.block([[row], [row]])
column = array[:, None]
columns = np.block([column, column])

print('Broadcasting:')
print(x[row, column], '\n')
print('Explicit:')
print(x[rows, columns])

Broadcasting:
[[1 5]
 [2 6]] 

Explicit:
[[1 5]
 [2 6]]


Boolean array indexing

In [6]:
x = np.arange(35).reshape(5, 7)
print(x[ [False, True, False,  True,  True], [False, True, False,  True,  True, False, False]])
print(x[ [1,3,4], [1,3,4]])

[ 8 24 32]
[ 8 24 32]


Combining advanced and basic indexing

In [21]:
x = np.arange(35).reshape(5, 7)
b = x > 20
x[b[:, 5], 1:3]

array([[22, 23],
       [29, 30]])

## 3.Field access

In [119]:
x = np.zeros((2, 2), dtype=[('a', np.int32), ('b', np.float64, (3, 3))])

print(x['a'].shape)
print(x['a'].dtype)

print(x['b'].shape)
print(x['b'].dtype)

print(x)

(2, 2)
int32
(2, 2, 3, 3)
float64
[[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
 [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]]


# Operations

## 1.Elementwise

In [141]:

A = np.array([1, 2])
B = np.ones(2, dtype=int)
print(A, '+', B, '=', A+B)
print(A, '-', B, '=', A-B)
print(A, '*', B, '=', A*B)
print(A, '/', B, '=', A/B)

[1 2] + [1 1] = [2 3]
[1 2] - [1 1] = [0 1]
[1 2] * [1 1] = [1 2]
[1 2] / [1 1] = [1. 2.]


## 2.Along axis

In [4]:
a = np.array([1, 2, 3, 4])
a.sum()
# Choose specific axis
b = a.reshape(2,2)
print(b, '\n')
print('axis = 0:')
print(b.sum(axis=0), '\n')

print('axis = 1:')
print(b.sum(axis=1))

[[1 2]
 [3 4]] 

axis = 0:
[4 6] 

axis = 1:
[3 7]


In [16]:
# Other functions

print('min: ', b.min())
print('max: ', b.max())
print('product: ', b.prod())
print('mean: ', b.mean())
print('standard deviation: ', b.std())

min:  1
max:  4
product:  24
mean:  2.5
standard deviation:  1.118033988749895


## 2.